### ISSUE TITLE
Error while trying to run the program: new_bbox = self.refresh_bbox(bb, indicates[0][0]) IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by superhrdina8** [RadekPazderka/pedestrian_tracking#1]
Hi, when Im trying to run you code I get this error: (see the picture)
Any chance you can help me with it? Thanks
<img width="1296" alt="Snímka obrazovky 2021-11-29 o 14 30 28" src="https://user-images.githubusercontent.com/34003257/143876992-3379c6de-a33c-4d24-9adc-be9922813118.png">

**Comment by RadekPazderka** [comment]
Python version from 3.9 -> 3.7 solved this problem.
